### PR TITLE
tests.services.ProjectService: Fix issue#10

### PR DESCRIPTION
**Pull request by srihithareddy-k**
Created  mocks for Actinia locations requests in test/mocks/ActiniaLocationsMocks.py
Added tests using the mocks for the ProjectService test.services.test_ActiniaProjectService.py

### CODE REVIEW

**Review by cwhite911 — APPROVED** [review]
Looks good!

**Review by cwhite911 — CHANGES_REQUESTED** [review]
Please add an additional test for creating a new project successfully. Otherwise, everything looks great!

**Comment by srihithareddy-k** [comment]
I have added the test for creating a new project successfully. Please review the changes.

**Review by cwhite911 — APPROVED** [review]
Looks good!

**Pull request merged**
